// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdmloghbaeqocmgfikjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbWxvZ2hiYWVxb2NtZ2Zpa2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzExMjgsImV4cCI6MjA2MjQ0NzEyOH0.huXYBK7bysrA4YwxrVnPSKuGLKFKWKYtspsHjZ9UO2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);